### ISSUE TITLE
Finalna uprava katalogu poziadaviek

### ISSUE THREAD

**Issue by Kraci** [TIS2018-FMFI/media-block-player#11]

**Comment by pavelpetrovic** [comment]
Precital som si vasu verziu katalogu poziadaviek z pred dvoch dni, je zatial velmi nizkej kvality a treba ho poriadne prepracovat, kym ho poslete zadavatelovi. Prikladam priklad uprav, ktore este nie su vsetky, co treba urobit, pozri poznamky v texte.
[Katalog.poziadaviek_s_upravami.docx](https://github.com/TIS2018-FMFI/media-block-player/files/2521637/Katalog.poziadaviek_s_upravami.docx)

**Comment by pavelpetrovic** [comment]
predtym ako to poslete zadavatelovi KP samozrejme chcem este raz vidiet

**Comment by pavelpetrovic** [comment]
vdaka za vysvetlenie, netusil som.

**Comment by pavelpetrovic** [comment]
dvaja clenovia, ktori su na stretnuti s cviciacim nevedia povedat, ci KP bol poslany zadavatelovi a to preto, ze nepouzivate issues poriadne, zlepsit pracu s issues!

**Comment by pavelpetrovic** [comment]
v aktualnej verzii mozno poslat KP zadavatelovi, poziadajte ho, aby si ho este raz dokladne prestudoval, lebo podla neho system vyviniete, zaroven ho poziadajte o stretnutie na prediskutovanie navrhu GUI.
mozete este upravit v KP: 
 - v perspektive produktu mi trochu lepsie vysvetlit, ako sa sw pri uceni pouziva a preco
 - domysliet a vyspecifikovat ako bude fungovat pridavanie a mazanie lekcii na server
 - 3.1.13.3.1. a 3.1.13.3.4. vyzera ako duplicita
 - random prehra kazdy blok prave raz?
 - 3.1.13.3.8. vyber jedneho
 - 3.1.13.4. pre uplnost by sa mohlo povedat - ak existuje viacero par.prekl. vyberie prvy znich
 - 3.1.15.1. znie trochu viacznacne

**Comment by pavelpetrovic** [comment]
- dotiahnut kde je ulozeny nazov lekcie
- o jazykoch sa nehovori v KP ale su v GUI, vyrieste to

**Comment by Kraci** [comment]
Spomenute poziadavky boli zapracovane a poslane zadavatelovi.
Dalsie info: https://github.com/TIS2018-FMFI/media-block-player/issues/18
