### ISSUE TITLE
Beta verzia

### ISSUE THREAD

**Issue by risnyovszky1** [TIS2018-FMFI/media-block-player#9]
vytvorenie beta verzii a testovanie js kniznice.

**Comment by risnyovszky1** [comment]
Vytvoril som beta 1.0. Spustit v localoste (napr wamp/xamp).

**Comment by Kraci** [comment]
Pozeral som to, super ze mame nejaku betu a vidime ze to funguje.
Dovod preco to musis spustat cez wamp, teda server, je ten ze tam mas priame cesty k suborom na tvrdo a to by lokalne prehrat takto neslo ze?
Budeme vediet takto isto fungovat ked tam nebude cesta na tvrdo ale budes si moct file vybrat z lokalneho disku alebo online kniznice?

A pls hod tuto issue aj do projektu, tam ju vies potom zaradit do dev finished a podobne ked to uz pouzivame, dikes.
